sudo: required
language: node_js
node_js:
    - 12
services:
    - mongodb
    - docker


before_install:
    - npm i -g npm@12
    - docker build -t pushp132129/vision-test -f Dockerfile.dev .

# install:
#     - npm install
    
script:
    - docker run pushp132129/vision-test npm test -- --coverage
    
    #Pushing images to the DockerHub
    after_success:
    - docker build -t pushp132129/vision-app 
    - docker build -t pushp132129/vision-mongo 

    #Logging into the Docker CLI
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #Pushing the images to the DockerHub
    - docker push pushp132129/vision-app
    - docker push pushp132129/vision-mongo
        