sudo: required

services:
    - docker


before_install:
    - docker build -t pushp132129/vision-app -f Dockerfile.dev .


    
script:
    - docker run -e CI=true pushp132129/vision-app npm test
    
    #Pushing images to the DockerHub
after_success:
    - docker build -t pushp132129/vision-app
    - docker build -t pushp132129/vision-database ./Database  
  

    #Logging into the Docker CLI
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #Pushing the images to the DockerHub
    - docker push pushp132129/vision-app
    - docker push pushp132129/vision-database
        