version: '3'
services: 
    app:
        container_name: app
        restart: always
        build: .
        ports: 
            - "3000:3000"
        environment: 
            - "mongodb://mongo:27017/visionDB"
        depends_on:
            - mongo

    mongo:
        container_name: mongo
        build: 
            dockerfile: Dockerfile
            context: ./Database
        volumes:
            - ./data:/data/db
        ports: 
            - "27017:27017"